import { h, createSSRApp, createApp } from 'vue';
import { Link, Head } from '@inertiajs/vue3';
import ZiggyPlugin from './plugins/inertia/ziggy';
import { Ziggy } from './ziggy';

// Ziggy's `route()` reads its config from `globalThis.Ziggy`. Assigning here
// (rather than only via the `@routes` blade directive's `window.route`) means
// the config is available in BOTH browser and SSR bundles — server-rendered
// links produce real URLs instead of empty placeholders. `resources/js/ziggy.js`
// is generated by `php artisan ziggy:generate` on `composer install` and on
// every `pnpm dev` / `pnpm build`; it's gitignored.
globalThis.Ziggy = Ziggy;

export async function setupApp({ App, props, plugin, isServer = false }) {
    const app = isServer
        ? createSSRApp({ render: () => h(App, props) })
        : createApp({ render: () => h(App, props) });

    app.use(plugin);

    // eslint-disable-next-line vue/no-reserved-component-names
    app.component('Link', Link);
    // eslint-disable-next-line vue/no-reserved-component-names
    app.component('Head', Head);

    app.use(ZiggyPlugin);

    return app;
}
