<?php

declare(strict_types=1);

namespace App\Tenancy\Bootstrappers;

use App\Models\Tenant as TenantModel;
use Illuminate\Support\Facades\URL;
use Stancl\Tenancy\Contracts\TenancyBootstrapper;
use Stancl\Tenancy\Contracts\Tenant;

/**
 * Rewrites the URL host while a tenant is active, so signed URLs (password
 * resets, email verification, magic links generated by the tenant context)
 * compute their signature against the tenant's host rather than the central
 * host. Without this, a link generated inside a tenant request but clicked
 * by a user on the tenant subdomain fails signature validation.
 *
 * Only registered when TENANCY_IDENTIFICATION=subdomain. In path mode the
 * host doesn't change between central and tenant URLs, so the bootstrapper
 * would be a no-op anyway — keeping it disabled in path mode avoids the
 * cost of a request-scoped URL rebind.
 *
 * To activate: uncomment the `SignedUrls::class` entry in the
 * `bootstrappers` list in config/tenancy.php when you switch to
 * subdomain mode.
 */
class SignedUrls implements TenancyBootstrapper
{
    public function bootstrap(Tenant $tenant): void
    {
        if (! $tenant instanceof TenantModel) {
            return;
        }

        $domain = $tenant->domains()->first()?->domain;

        if ($domain === null) {
            return;
        }

        $scheme = parse_url((string) config('app.url'), PHP_URL_SCHEME) ?: 'https';

        URL::forceRootUrl($scheme.'://'.$domain);
    }

    public function revert(): void
    {
        URL::forceRootUrl((string) config('app.url'));
    }
}
